packages:
  - 'apps/*'
  - 'packages/*'
nodeLinker: hoisted
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  sharp: true
  unrs-resolver: true
overrides:
  react: 19.1.0
  react-dom: 19.1.0
