import { CSSProperties } from 'react';
 
const styles: Record<string, CSSProperties> = {
  navbar: {
    background: '#5BA4CF',
    height: '60px',
    padding: '0 32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  navBrand: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: '1.2rem',
    fontWeight: 700,
    color: '#ffffff',
    letterSpacing: '-0.01em',
  },
  navRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
  },
  navUserName: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.875rem',
    color: 'rgba(255,255,255,0.9)',
  },
  avatar: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    background: 'rgba(255,255,255,0.25)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'Poppins', sans-serif",
    fontSize: '0.8rem',
    fontWeight: 600,
    color: '#ffffff',
  },
  page: {
    maxWidth: '960px',
    margin: '0 auto',
    padding: '32px 24px',
  },
  greeting: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: '1.5rem',
    fontWeight: 700,
    color: '#3A3A3A',
    marginBottom: '4px',
  },
  greetingSub: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.875rem',
    color: '#6b7280',
    marginBottom: '28px',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '14px',
    marginBottom: '32px',
  },
  statCard: {
    background: '#ffffff',
    borderRadius: '10px',
    padding: '20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.07)',
    borderLeft: '4px solid #5BA4CF',
  },
  statCardAccent: {
    borderLeftColor: '#9FD8A3',
  },
  statCardYellow: {
    borderLeftColor: '#F5E497',
  },
  statLabel: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.75rem',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '8px',
  },
  statValue: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: '2rem',
    fontWeight: 700,
    color: '#3A3A3A',
    lineHeight: 1,
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '14px',
  },
  sectionTitle: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: '1rem',
    fontWeight: 600,
    color: '#3A3A3A',
  },
  btnNew: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.8125rem',
    fontWeight: 500,
    background: '#9FD8A3',
    color: '#1a5c1e',
    border: 'none',
    borderRadius: '6px',
    padding: '7px 16px',
    cursor: 'pointer',
  },
  resourceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    marginBottom: '32px',
  },
  resourceCard: {
    background: '#ffffff',
    borderRadius: '10px',
    border: '1px solid #e2e5ea',
    padding: '16px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    boxShadow: '0 1px 3px rgba(0,0,0,0.07)',
  },
  resourceTitle: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.9375rem',
    fontWeight: 500,
    color: '#3A3A3A',
    marginBottom: '4px',
  },
  resourceMeta: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.75rem',
    color: '#6b7280',
  },
  resourceActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  badge: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.6875rem',
    fontWeight: 500,
    padding: '3px 10px',
    borderRadius: '20px',
  },
  badgeValidated: {
    background: '#dcf5e0',
    color: '#1a5c1e',
  },
  badgePending: {
    background: '#fef9e0',
    color: '#7a6200',
  },
  badgeSuspended: {
    background: '#fde8e8',
    color: '#8b1a1a',
  },
  btnEdit: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.75rem',
    color: '#6b7280',
    background: 'transparent',
    border: '1px solid #e2e5ea',
    borderRadius: '6px',
    padding: '5px 12px',
    cursor: 'pointer',
  },
  progressGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  progressCard: {
    background: '#ffffff',
    borderRadius: '10px',
    border: '1px solid #e2e5ea',
    padding: '16px 20px',
    boxShadow: '0 1px 3px rgba(0,0,0,0.07)',
  },
  progressTitle: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.875rem',
    fontWeight: 500,
    color: '#3A3A3A',
    marginBottom: '3px',
  },
  progressCat: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.6875rem',
    color: '#6b7280',
    marginBottom: '12px',
  },
  progressBarBg: {
    height: '6px',
    background: '#F6F7F9',
    borderRadius: '3px',
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    borderRadius: '3px',
    background: '#5BA4CF',
  },
  progressBarAside: {
    background: '#F5E497',
  },
  quote: {
    fontFamily: "'Lora', serif",
    fontStyle: 'italic',
    fontSize: '0.9375rem',
    color: '#6b7280',
    borderLeft: '3px solid #5BA4CF',
    padding: '12px 20px',
    marginTop: '32px',
    background: '#ffffff',
    borderRadius: '0 6px 6px 0',
  },
  loadingScreen: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'Open Sans', sans-serif",
    color: '#6b7280',
    background: '#F6F7F9',
  },
};

export default styles