import React from 'react';
 
const s: Record<string, React.CSSProperties> = {
  // ── Layout ──────────────────────────────────────────
  page: {
    minHeight: '100vh',
    background: '#F6F7F9',
    fontFamily: "'Open Sans', sans-serif",
  },
  header: {
    background: '#5BA4CF',
    padding: '20px 32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: '1.25rem',
    fontWeight: 700,
    color: '#fff',
    margin: 0,
  },
  headerBack: {
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.8125rem',
    color: 'rgba(255,255,255,0.85)',
    background: 'rgba(255,255,255,0.15)',
    border: '1px solid rgba(255,255,255,0.3)',
    borderRadius: 6,
    padding: '6px 14px',
    cursor: 'pointer',
  },
  content: {
    maxWidth: 1100,
    margin: '0 auto',
    padding: '28px 24px',
  },
 
  // ── Toolbar ─────────────────────────────────────────
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 12,
    flexWrap: 'wrap' as const,
  },
  filters: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap' as const,
  },
  select: {
    height: 38,
    padding: '0 12px',
    border: '1px solid #d1d5db',
    borderRadius: 6,
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.875rem',
    color: '#3A3A3A',
    background: '#fff',
    cursor: 'pointer',
    outline: 'none',
  },
  btnAdd: {
    height: 38,
    padding: '0 18px',
    background: '#9FD8A3',
    color: '#1a5c1e',
    border: 'none',
    borderRadius: 6,
    fontFamily: "'Poppins', sans-serif",
    fontSize: '0.875rem',
    fontWeight: 600,
    cursor: 'pointer',
    whiteSpace: 'nowrap' as const,
  },
 
  // ── Table ────────────────────────────────────────────
  tableWrap: {
    background: '#fff',
    borderRadius: 10,
    border: '1px solid #e2e5ea',
    overflow: 'hidden',
    boxShadow: '0 1px 3px rgba(0,0,0,0.07)',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse' as const,
    fontSize: '0.875rem',
  },
  thead: {
    background: '#f8f9fb',
    borderBottom: '1px solid #e2e5ea',
  },
  th: {
    padding: '12px 16px',
    textAlign: 'left' as const,
    fontFamily: "'Poppins', sans-serif",
    fontSize: '0.75rem',
    fontWeight: 600,
    color: '#6b7280',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
    whiteSpace: 'nowrap' as const,
  },
  td: {
    padding: '14px 16px',
    borderBottom: '1px solid #f0f2f5',
    color: '#3A3A3A',
    verticalAlign: 'middle' as const,
  },
  tdMuted: {
    padding: '14px 16px',
    borderBottom: '1px solid #f0f2f5',
    color: '#9ca3af',
    fontSize: '0.8125rem',
    verticalAlign: 'middle' as const,
  },
  trHover: {
    background: '#fafbfc',
  },
  emptyRow: {
    padding: '48px 16px',
    textAlign: 'center' as const,
    color: '#9ca3af',
    fontStyle: 'italic',
  },
 
  // ── Badges ───────────────────────────────────────────
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '3px 10px',
    borderRadius: 20,
    fontSize: '0.6875rem',
    fontWeight: 600,
    whiteSpace: 'nowrap' as const,
  },
  badgeValidated: { background: '#dcf5e0', color: '#1a5c1e' },
  badgePending:   { background: '#fef9e0', color: '#7a6200' },
  badgeSuspended: { background: '#fde8e8', color: '#8b1a1a' },
 
  // ── Action buttons ────────────────────────────────────
  actions: {
    display: 'flex',
    gap: 6,
    alignItems: 'center',
  },
  btnEdit: {
    height: 30,
    padding: '0 10px',
    background: 'transparent',
    border: '1px solid #d1d5db',
    borderRadius: 5,
    fontSize: '0.75rem',
    color: '#3A3A3A',
    cursor: 'pointer',
    fontFamily: "'Open Sans', sans-serif",
  },
  btnSuspend: {
    height: 30,
    padding: '0 10px',
    background: 'transparent',
    border: '1px solid #f5e497',
    borderRadius: 5,
    fontSize: '0.75rem',
    color: '#7a6200',
    cursor: 'pointer',
    fontFamily: "'Open Sans', sans-serif",
  },
  btnReactivate: {
    height: 30,
    padding: '0 10px',
    background: 'transparent',
    border: '1px solid #9FD8A3',
    borderRadius: 5,
    fontSize: '0.75rem',
    color: '#1a5c1e',
    cursor: 'pointer',
    fontFamily: "'Open Sans', sans-serif",
  },
  btnDelete: {
    height: 30,
    padding: '0 10px',
    background: 'transparent',
    border: '1px solid #fca5a5',
    borderRadius: 5,
    fontSize: '0.75rem',
    color: '#c53030',
    cursor: 'pointer',
    fontFamily: "'Open Sans', sans-serif",
  },
 
  // ── Modal ─────────────────────────────────────────────
  modalOverlay: {
    position: 'fixed' as const,
    inset: 0,
    background: 'rgba(0,0,0,0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    padding: 24,
  },
  modal: {
    background: '#fff',
    borderRadius: 12,
    padding: '28px 32px',
    width: '100%',
    maxWidth: 560,
    maxHeight: '90vh',
    overflowY: 'auto' as const,
    boxShadow: '0 8px 32px rgba(0,0,0,0.15)',
  },
  modalTitle: {
    fontFamily: "'Poppins', sans-serif",
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#3A3A3A',
    margin: '0 0 20px',
  },
  modalActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 24,
  },
  btnCancel: {
    height: 38,
    padding: '0 16px',
    background: 'transparent',
    border: '1px solid #d1d5db',
    borderRadius: 6,
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.875rem',
    color: '#6b7280',
    cursor: 'pointer',
  },
  btnConfirmDelete: {
    height: 38,
    padding: '0 16px',
    background: '#e53e3e',
    border: 'none',
    borderRadius: 6,
    fontFamily: "'Poppins', sans-serif",
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#fff',
    cursor: 'pointer',
  },
  btnSave: {
    height: 38,
    padding: '0 20px',
    background: '#5BA4CF',
    border: 'none',
    borderRadius: 6,
    fontFamily: "'Poppins', sans-serif",
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#fff',
    cursor: 'pointer',
  },
 
  // ── Form ──────────────────────────────────────────────
  field: {
    marginBottom: 16,
  },
  label: {
    display: 'block',
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.75rem',
    fontWeight: 600,
    color: '#6b7280',
    marginBottom: 6,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  input: {
    width: '100%',
    height: 40,
    padding: '0 12px',
    border: '1px solid #d1d5db',
    borderRadius: 6,
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.9375rem',
    color: '#3A3A3A',
    background: '#fafafa',
    boxSizing: 'border-box' as const,
    outline: 'none',
  },
  textarea: {
    width: '100%',
    padding: '10px 12px',
    border: '1px solid #d1d5db',
    borderRadius: 6,
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.9375rem',
    color: '#3A3A3A',
    background: '#fafafa',
    boxSizing: 'border-box' as const,
    outline: 'none',
    resize: 'vertical' as const,
    minHeight: 90,
  },
  formSelect: {
    width: '100%',
    height: 40,
    padding: '0 12px',
    border: '1px solid #d1d5db',
    borderRadius: 6,
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.9375rem',
    color: '#3A3A3A',
    background: '#fafafa',
    outline: 'none',
    cursor: 'pointer',
  },
 
  // ── Toast ─────────────────────────────────────────────
  toastContainer: {
    position: 'fixed' as const,
    bottom: 24,
    right: 24,
    zIndex: 2000,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 10,
  },
  toast: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '12px 18px',
    borderRadius: 8,
    fontFamily: "'Open Sans', sans-serif",
    fontSize: '0.875rem',
    fontWeight: 500,
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    animation: 'slideIn 0.2s ease',
    minWidth: 260,
  },
  toastSuccess: {
    background: '#dcf5e0',
    color: '#1a5c1e',
    border: '1px solid #9FD8A3',
  },
  toastError: {
    background: '#fde8e8',
    color: '#8b1a1a',
    border: '1px solid #fca5a5',
  },
};
 
export default s;
 